name: Code Convention Checks

on:
  push:

jobs:
  Setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TELESCOPE_ENABLED: false
      MICROSCOPE_ENABLED: true
      CACHE_STORE: array
      LOG_CHANNEL: null
      APP_ENV: staging
      APP_KEY: ${{ secrets.APP_KEY }}

    strategy:
      fail-fast: false
      matrix:
        php-versions: ["8.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # ref: "staging"
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, iconv
          coverage: none

      - name: Cache Composer dependencies
        id: cache-vendor
        uses: actions/cache@v4
        with:
          path: |
            vendor
            storage/framework/cache/microscope
          key: composer-${{ hashFiles('**/composer.lock') }}
          # In case of cache miss, restore the previous vendor
          # folder and continue the installation from that...
          restore-keys: composer-

      - name: Install Composer dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true' # Skip if cache hit
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Require microscope
        if: steps.cache-vendor.outputs.cache-hit != 'true' # Skip if cache hit
        run: composer require imanghafoori/laravel-microscope

      - name: Check namespaces
        run: php artisan check:psr4 --nofix

      - name: Check imports
        run: php artisan check:imports --folder=tests,seeders,factories,routes,app --nofix

      - name: Check For Empty Comments
        run: php artisan check:empty_comments --nofix

      - name: Check Aliases
        run: php artisan check:alias --nofix

      - name: Check For extra semi colons
        run: php artisan check:extra_semi_colons --nofix

      - name: Check For env calls in the `app` folder
        run: php artisan check:bad_practices
